### ISSUE TITLE
Implement FM4002

### ISSUE THREAD

**Issue by ArielSAdamsNASA** [nasa/FM#111]
**Checklist (Please check before submitting)**

* [X] I reviewed the [Contributing Guide](https://github.com/nasa/FM/blob/main/CONTRIBUTING.md).
* [X] I reviewed the [README file](https://github.com/nasa/FM/blob/main/README.md) to see if the feature is in the major future work.
* [X] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
JIRA has the requirement, FM4002. This needs to be implemented or deleted on JIRA. 

**Describe the solution you'd like**
If implemented, the requirement and implementation must be added to [fm_FunctionalRequirements.csv](https://github.com/nasa/FM/blob/main/docs/fm_FunctionalRequirements.csv) and the Requirements Document and Traceability for Equuleus RC2. 

**Describe alternatives you've considered**
Remove the requirement in JIRA. 

**Requester Info**
Ariel Adams, MCSG TECH.

**Comment by skliper** [comment]
@ArielSAdamsNASA - looks to me like FM4002 status on JIRA is cancelled, so I wouldn't expect it to be included in the requirements export.
