### ISSUE TITLE
FM is incompatible with recent OSAL API changes

### ISSUE THREAD

**Issue by mbenson1** [nasa/FM#3]
This is regarding OSAL 5.0.3-bv.  FM calls OS_opendir, OS_readdir, and OS_closedir which were removed in favor of OS_DirectoryOpen, OS_DirectoryRead, and OS_DirectoryClose.  I expect to see other issues as I make fixes to pass unit testing.  I will post them here.

**Comment by cyberxml** [comment]
confirming

**Comment by skliper** [comment]
Updated for Caelum compatibility in 142eec97a0cb1b4cbf9a93ecc80465ee72927648, Draco in c1ef41a4b5aa738741a27cf2f60fc85db0473a28
